### ISSUE TITLE
Request AMD Ryzen 7 5700

### ISSUE THREAD

**Issue by ypraw** [aviezab/xanmod-arch#1]
Hallo mas , apakabar??? 
akun Tele hilang nampaknya wkwkwkw 

btw request dong buat AMD Ryzen 7 5700U

**Comment by aviezab** [comment]
Yoi @ypraw Nin. Coba nanti tak cari di tele ya.
Itu bisa buat Ryzen 7 5700, Zen 3 kan?
Cobain dah penasaran juga ga ada device buat test

**Comment by ypraw** [comment]
telenya yg mana? aku masih nyimpen nomor yg 6200 tapi ngga ada Wanya, atau telenya.
nanti tak coba deh, sekalian kalo ada lowongan ulet keket, bosen pake node nih 😂😂😂

**Comment by mnabila** [comment]
nah +1 untuk akun telenya mas @aviezab sekarang ganti username apa ?
 beberapa bulan yang lalu sempet dicariin anak anak manjaro id klok ga salah inget.

**Comment by aviezab** [comment]
Waduh sampai dicariin ya, artis bukan, orang peting juga bukan padahal 😂

@mnabila Aku barusan chat ypraw. Minta ke dia aja ya. Aduh jadi rame deh ini github hahaha..

**Comment by mnabila** [comment]
siap mas @aviezab
